version: "3.9"
services:
  postgres:
    container_name: metadata_postgres
    image: postgres:latest
    ports:
      - "5430:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/pgdata_nv
    volumes:
      - ./init.sh:/docker-entrypoint-initdb.d/init.sh
